### ISSUE TITLE
种豆得豆&京喜工厂四人团

### ISSUE THREAD

**Issue by zhongwangninja** [zhongwangninja/MyActions#2]
上了车之后，只有种豆和京喜工厂打工有助力不满的风险，所以四人只做这两项的互助。

@zhongwangninja 
种豆得豆 xne2y45jxvlhy3fuhp22ostyrurihzjebzagkuq
京喜工厂 0-0u2Mapf7_YSBtPWP3iYQ==

@wheatwee
种豆得豆 btgrwkzaimj5uthjltldfpmsba
京喜工厂 H0gSmUINiijOL37Mtr4Cvg==

**Comment by seek1987** [comment]
京喜工厂
g7nwKXtEV6oj7xkUzCVrIw==
种豆得豆
e7lhibzb3zek3sx4yrxmdxgzncwekdoe56mzecy

**Comment by zhongwangninja** [comment]
最后一个人迟迟不来，我们三个先搞起来吧，明天就可以开始助力了。

@zhongwangninja @wheatwee @seek1987 助力码如下添加即可，脚本碰到自己的助力会跳过执行。大家可以看下自己的助力码是不是对的。

种豆
xne2y45jxvlhy3fuhp22ostyrurihzjebzagkuq@btgrwkzaimj5uthjltldfpmsba@e7lhibzb3zek3sx4yrxmdxgzncwekdoe56mzecy

京喜工厂-招工
0-0u2Mapf7_YSBtPWP3iYQ==@H0gSmUINiijOL37Mtr4Cvg==@g7nwKXtEV6oj7xkUzCVrIw==

**Comment by zhongwangninja** [comment]
助力码添加好了

**Comment by wheatwee** [comment]
@zhongwangninja  好的

**Comment by wheatwee** [comment]
@seek1987  刚刚发现惊喜工厂每天是限额助力3位，抱歉今天没有给你助力上。已经添加到小号了，明天就能给你助力上

**Comment by HZJGH** [comment]
添加了

**Comment by zhongwangninja** [comment]
@HZJGH 是这三个都加上了吗？https://github.com/zhongwangninja/MyActions/issues/2#issuecomment-747416152

我们三人也会加上你的助力，你的助力码发下吧，我把四个人的助力码整理出来

**Comment by pythonxue** [comment]
中豆 jk45nf2g2bhkjafmwwo66bymp4
京喜工厂 u7Tng839KoEHbuAQRc6VEQ==

**Comment by zhongwangninja** [comment]
@seek1987 的京喜助力好像有些问题，暂时从助力表中删除了，如果无法互助的话可以先删掉给我们的助力。

最新的助力是 @zhongwangninja @wheatwee @pythonxue 三人，助力码如下，大家可以检查下助力码是否有误，三人互助明天开始：

种豆得豆
xne2y45jxvlhy3fuhp22ostyrurihzjebzagkuq@btgrwkzaimj5uthjltldfpmsba@jk45nf2g2bhkjafmwwo66bymp4

京喜工厂-招工
0-0u2Mapf7_YSBtPWP3iYQ==@H0gSmUINiijOL37Mtr4Cvg==@u7Tng839KoEHbuAQRc6VEQ==

**Comment by zhongwangninja** [comment]
最新助力码更新好了

**Comment by wheatwee** [comment]
@zhongwangninja 收到，搞定

**Comment by wheatwee** [comment]
@zhongwangninja 今天全挂了，你有看到什么新方案吗？有的话信息共享一下啊，哈哈哈
